/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2022-04-25 09:11:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.resources.admin.relatorio;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class content_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"relatorio/relatorio.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div  class=\"hexagon-menu clear\">\r\n");
      out.write("                                    <div  class=\"hexagon-item\">\r\n");
      out.write("                                        <div class=\"hex-item\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div></div>\r\n");
      out.write("                                            <div></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"hex-item\">\r\n");
      out.write("                                            <div></div>\r\n");
      out.write("                                            <div></div>\r\n");
      out.write("                                        \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <a href=\"#\" onclick=\"loadPage('main')\" class=\"hex-content\">\r\n");
      out.write("                                            <span class=\"hex-content-inner\">\r\n");
      out.write("                                                <span class=\"icon\">\r\n");
      out.write("                                                    <i class=\"tf-ion-ios-home\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                                <span class=\"title\">Início</span>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                            <svg viewbox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br/><br/>\r\n");
      out.write("<div id=\"reportPage\" style=\"width: 100%; height: 100%;\">\r\n");
      out.write("\t  <div style=\"width: 50%; margin-bottom: 3%; margin-left: auto; margin-right: auto;\">\r\n");
      out.write("\t   \r\n");
      out.write("\t    <div id=\"minhadiv\">\r\n");
      out.write("\t    \t\r\n");
      out.write("\t       <input type=\"date\" onChange = \"SENAI.biblioteca.teste()\" id=\"valorBusca\"/>\r\n");
      out.write("\t      \r\n");
      out.write("\t       \r\n");
      out.write("\t       <input type=\"date\" onChange = \"SENAI.biblioteca.teste()\" id=\"valorBusca2\"/>\r\n");
      out.write("\t       \r\n");
      out.write("\t     </div>\r\n");
      out.write("\t       <canvas  id=\"myChart2\" class=\"line-chart2\">\r\n");
      out.write("\t       </canvas>\r\n");
      out.write("\t    <div id=\"example\" style=\"text-align: center;\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</div>\r\n");
      out.write("<button id=\"downloadPdf\" style=\"float: right;\" class=\"btn btn-success\">Baixar PDF</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
